### ISSUE TITLE
Channel Suggestions

### ISSUE THREAD

**Issue by weldon1045** [Animenosekai/japanterebi-xmltv#1]
Hello, I'm currently contributing to a Japanese IPTV list and it seems you have coverage for almost all of the channels our list currently has.

In this case, I would like to see if you could these EPG feeds, in which case if you're able to, I'd appreciate it a lot.

- Space Shower TV (音楽・ライブ！　スペースシャワーTV HD)
- MONDO TV (MONDOTV HD)
- Music Japan (ミュージック・ジャパン)
- Tokyo MX2
- TSS (新広島テレビ)

Thanks in advance.

**Comment by Animenosekai** [comment]
I'll see what I can do but I need to add them to [`iptv-org/epg`](https://github.com/iptv-org/epg)

**Comment by Animenosekai** [comment]
Maybe they are on JCOM ?

**Comment by weldon1045** [comment]
Yep:
https://www2.myjcom.jp/tv/cs-list/?c=&t=1&s=191_11&g=fmovie&d=20240726&sc_pid=my_epg_globalnavi_cs-list
https://tvguide.myjcom.jp/?area_id=108
https://tvguide.myjcom.jp/?area_id=10046

Music Japan is on Sky Perfect:
https://www.skyperfectv.co.jp/program/schedule/premium/channel:639/date:240725/

It seems many IDs already exist on iptv-org, except for TSS.

**Comment by Animenosekai** [comment]
Adding TSS, Space Shower TV and MONDO TV right now.

I'll need a bit more work to be done in order to add Tokyo MX2 (maybe using the official Tokyo MX website ?).

**Comment by Animenosekai** [comment]
> * Space Shower TV (音楽・ライブ！　スペースシャワーTV HD)
> * MONDO TV (MONDOTV HD)

They are already in the EPG, just didn't have any IDs attached to them, I'm currently adding them.

**Comment by Animenosekai** [comment]
`TSS (新広島テレビ)` doesn't seem to have an ID in [`iptv-org/database`](https://github.com/iptv-org/database), should I add a temporary ID for you to use ?

**Comment by Animenosekai** [comment]
Alright seems pretty easy for Tokyo MX2, the official website uses <https://s.mxtv.jp/bangumi_file/json01/SV2EPGYYYYMMDD.json>

> Example: <https://s.mxtv.jp/bangumi_file/json01/SV2EPG20240727.json>

**Comment by weldon1045** [comment]
> `TSS (新広島テレビ)` doesn't seem to have an ID in [`iptv-org/database`](https://github.com/iptv-org/database), should I add a temporary ID for you to use ?

Yep, it shouldn't be a problem.

**Comment by weldon1045** [comment]
In regards to Music Japan, Is the process done in a similar way to JCOM?

**Comment by Animenosekai** [comment]
For Music Japan, it needs to add another site to the [`iptv-org/epg`](https://github.com/iptv-org/epg) repo (for example Sky Perfect) and write a parser.

**Comment by weldon1045** [comment]
Another alternative I was thinking of was to consider the Bangumi.org website which has EPG for each and every Japanese channel, but I don't know if that website also requires to be added to the repository.

**Comment by Animenosekai** [comment]
@weldon1045 

> Another alternative I was thinking of was to consider the Bangumi.org website which has EPG for each and every Japanese channel, but I don't know if that website also requires to be added to the repository.

The problem with [`bangumi.org`](https://bangumi.org) is that their EPG is purely HTML-based, meaning that to parse the information, you need to download the whole page to parse it (which is also weak to any change of the website).

Moreover, only the basic informations are here (Title, Description and Time). To try retrieving more data, there is a need to open the page of each program.

To be fair it might be possible to download the app and try to understand how their API works from here but for now JCOM's EPG works best.

**Comment by Animenosekai** [comment]
(Btw just implemented Tokyo MX2)

**Comment by Animenosekai** [comment]
Alright let's get to implementing SkyPerfect

**Comment by Animenosekai** [comment]
Alright did everything possible to add all listed channels (+ even more channels since [SkyPerfect!](https://www.skyperfectv.co.jp) literally has 137 channels available).

Closing this issue since this repository uses the unmerged content and should have the issue solved (feel free to open it again if you feel the need to!)

> [!TIP]  
> Follow the related upstream PRs [iptv-org/database#13067](https://github.com/iptv-org/database/pull/13067) and [iptv-org/epg#2409](https://github.com/iptv-org/epg/pull/2409).
